version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=5000
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - minio
      - redis
    volumes:
      - .:/app
      - /app/node_modules # tránh ghi đè node_modules trong container

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  redis:
    image: redis/redis-stack-server:latest
    # Sử dụng image Redis mới nhất
    container_name: redis
    restart: unless-stopped # Redis sẽ tự động khởi động lại trừ khi dừng thủ công
    ports:
      - '6379:6379' # Ánh xạ cổng Redis vào máy chủ
    volumes:
      - redis_data:/data # Sử dụng volume để lưu trữ dữ liệu Redis

volumes:
  mysql_data:
  minio_data:
  redis_data:
